<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE boksamling [
<!ELEMENT boksamling (bok+)>
<!ELEMENT bok (titel, författare+, sidor?, pris, förlag, utgivningsår, omslag?)>
<!ATTLIST bok isbn CDATA #REQUIRED>
<!ELEMENT författare (namn)>
<!ELEMENT namn (förnamn, efternamn)>
<!ELEMENT förnamn (#PCDATA)>
<!ELEMENT efternamn (#PCDATA)>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT sidor (#PCDATA)>
<!ELEMENT pris (#PCDATA)>
<!ATTLIST pris valuta CDATA "SEK">
<!ELEMENT förlag (#PCDATA)>
<!ELEMENT utgivningsår (#PCDATA)>
<!ELEMENT omslag (#PCDATA)>
]>
<boksamling>
    <bok isbn="012301231">
        <titel>XML Content and Data</titel>
        <författare>
            <namn>
                <förnamn>Kelly</förnamn>
                <efternamn>Carey</efternamn>
            </namn>
        </författare>
        <författare>
            <namn>
                <förnamn>Stanko</förnamn>
                <efternamn>Blatnik</efternamn>
            </namn>
        </författare>
        <sidor>408</sidor>
        <pris valuta="SEK">410</pris>
        <förlag>Prentic-Hall</förlag>
        <utgivningsår>2002</utgivningsår>
        <omslag>paperback</omslag>
    </bok>
</boksamling>